/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Nciz.RegisterRawatJalan.frame.dialog;

import ian.RegisterRawatJalan.DatabaseHelper.koneksiReport;
import Nciz.RegisterRawatJalan.Entity.DBVirtualRiwayatPenyakit;
import Nciz.RegisterRawatJalan.Entity.DbVirtualRiwayatDokter;
import com.stripbandunk.jwidget.model.DynamicTableModel;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ncizh
 */
public class RekamMedis extends javax.swing.JDialog {

    /**
     * Creates new form RekamMedis
     */
    private DynamicTableModel<DbVirtualRiwayatDokter> dynamicTableModel;
    private DynamicTableModel<DBVirtualRiwayatPenyakit> dynamicTableModel1;

    public RekamMedis() {
        setModal(true);
        initComponents();
        dynamicTableModel = new DynamicTableModel<>(DbVirtualRiwayatDokter.class);
        tabelRiwayatResepDokter.setShowGrid(true);
        tabelRiwayatResepDokter.setRowHeight(24);
        tabelRiwayatResepDokter.setDynamicModel(dynamicTableModel);
    }

    public JLabel getLblIdPeriksa() {
        return lblIdPeriksa;
    }

    public JLabel getLblNamaPasien() {
        return lblNamaPasien;
    }

    public JLabel getlblUmur() {
        return lblUmur;
    }

    public JLabel getlblAlamat() {
        return lblAlamat;
    }

    public DynamicTableModel<DbVirtualRiwayatDokter> getDynamicTableModel() {
        return dynamicTableModel;
    }

    public DynamicTableModel<DBVirtualRiwayatPenyakit> getDynamicTableModel1() {
        return dynamicTableModel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImageBackground1 = new wordpress.eecchhoo.jpanelimagebackground.JPanelImageBackground();
        lblNamaPasien = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblUmur = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelRiwayatResepDokter = new com.stripbandunk.jwidget.JDynamicTable();
        btnCetak = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblIdPeriksa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rekam Medis");
        setMinimumSize(new java.awt.Dimension(920, 600));
        setModal(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setPreferredSize(new java.awt.Dimension(920, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelImageBackground1.setGambar(new java.io.File("E:\\Zona Terlarang\\images\\Wallpaper dengan corak menarik\\929678-1366x768-blue-water-ripple.jpg"));
        jPanelImageBackground1.setGambarDrawType(1);
        jPanelImageBackground1.setMinimumSize(new java.awt.Dimension(1000, 1200));
        jPanelImageBackground1.setName(""); // NOI18N
        jPanelImageBackground1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelImageBackground1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNamaPasien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNamaPasien.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaPasien.setText("Nama Pasien");
        jPanelImageBackground1.add(lblNamaPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Pasien ");
        jPanelImageBackground1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 102, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Umur");
        jPanelImageBackground1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");
        jPanelImageBackground1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        lblUmur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUmur.setForeground(new java.awt.Color(255, 255, 255));
        lblUmur.setText("Umur");
        jPanelImageBackground1.add(lblUmur, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        lblAlamat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAlamat.setForeground(new java.awt.Color(255, 255, 255));
        lblAlamat.setText("Alamat");
        jPanelImageBackground1.add(lblAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Riwayat Resep Dokter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), java.awt.Color.white)); // NOI18N
        jPanel3.setOpaque(false);

        tabelRiwayatResepDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tabelRiwayatResepDokter);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelImageBackground1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 840, -1));

        btnCetak.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nciz/RegisterRawatJalan/Gambar/cetak1.png"))); // NOI18N
        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        jPanelImageBackground1.add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 120, 40));

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nciz/RegisterRawatJalan/Gambar/batalkan.png"))); // NOI18N
        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanelImageBackground1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 120, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID periksa");
        jPanelImageBackground1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        lblIdPeriksa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIdPeriksa.setForeground(new java.awt.Color(255, 255, 255));
        lblIdPeriksa.setText("ID periksa");
        jPanelImageBackground1.add(lblIdPeriksa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        getContentPane().add(jPanelImageBackground1, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleName("Detail Riwayat Penyakit & Resep Dokter");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        dynamicTableModel.clear();
    }//GEN-LAST:event_formWindowClosing

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnCetakActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private wordpress.eecchhoo.jpanelimagebackground.JPanelImageBackground jPanelImageBackground1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblIdPeriksa;
    private javax.swing.JLabel lblNamaPasien;
    private javax.swing.JLabel lblUmur;
    private com.stripbandunk.jwidget.JDynamicTable tabelRiwayatResepDokter;
    // End of variables declaration//GEN-END:variables

    
}
