/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Nciz.RegisterRawatJalan.frame.panel;

import Nciz.RegisterRawatJalan.event.MenuUtamaEvent;
import Nciz.RegisterRawatJalan.event.MenuUtamaListener;

/**
 *
 * @author Ncizh
 */
public class LetakMenu extends javax.swing.JPanel {

    /**
     * Creates new form LetakMenu
     */
    public LetakMenu() {
        initComponents();
      
        
    }

    public RenderDokter getRenderDokter1() {
        return renderDokter1;
    }

    public RenderObat getRenderObat1() {
        return renderObat1;
    }

    public RenderPembayaran getRenderPembayaran1() {
        return renderPembayaran1;
    }

    public RenderPeriksa getRenderPeriksa1() {
        return renderPeriksa1;
    }

    public RenderUser getRenderUser1() {
        return renderUser1;
    }

    public RenderButton getBtnPasien() {
        return btnPasien;
    }

    public void addUtamaListener(MenuUtamaListener menuUtamaListener) {
        listenerList.add(MenuUtamaListener.class, menuUtamaListener);
    }

    public void removeUtamaListener(MenuUtamaListener menuUtamaListener) {
        listenerList.remove(MenuUtamaListener.class, menuUtamaListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnPasien = new Nciz.RegisterRawatJalan.frame.panel.RenderButton();
        renderPembayaran1 = new Nciz.RegisterRawatJalan.frame.panel.RenderPembayaran();
        renderDokter1 = new Nciz.RegisterRawatJalan.frame.panel.RenderDokter();
        renderUser1 = new Nciz.RegisterRawatJalan.frame.panel.RenderUser();
        renderObat1 = new Nciz.RegisterRawatJalan.frame.panel.RenderObat();
        renderPeriksa1 = new Nciz.RegisterRawatJalan.frame.panel.RenderPeriksa();
        jLabel3 = new javax.swing.JLabel();

        setOpaque(false);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        btnPasien.setForeground(new java.awt.Color(255, 255, 255));
        btnPasien.setText("PASIEN");
        btnPasien.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnPasien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPasien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasienActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 94;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(btnPasien, gridBagConstraints);

        renderPembayaran1.setForeground(new java.awt.Color(255, 255, 255));
        renderPembayaran1.setText("PEMBAYARAN");
        renderPembayaran1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        renderPembayaran1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        renderPembayaran1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        renderPembayaran1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        renderPembayaran1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renderPembayaran1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 198;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        add(renderPembayaran1, gridBagConstraints);

        renderDokter1.setForeground(new java.awt.Color(255, 255, 255));
        renderDokter1.setText("DOKTER");
        renderDokter1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        renderDokter1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        renderDokter1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        renderDokter1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        renderDokter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renderDokter1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 168;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(renderDokter1, gridBagConstraints);

        renderUser1.setForeground(new java.awt.Color(255, 255, 255));
        renderUser1.setText("USER");
        renderUser1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        renderUser1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        renderUser1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        renderUser1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        renderUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renderUser1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 120;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(renderUser1, gridBagConstraints);

        renderObat1.setForeground(new java.awt.Color(255, 255, 255));
        renderObat1.setText("OBAT");
        renderObat1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        renderObat1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        renderObat1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        renderObat1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        renderObat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renderObat1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 120;
        gridBagConstraints.gridy = 50;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        add(renderObat1, gridBagConstraints);

        renderPeriksa1.setForeground(new java.awt.Color(255, 255, 255));
        renderPeriksa1.setText("PERIKSA");
        renderPeriksa1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        renderPeriksa1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        renderPeriksa1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        renderPeriksa1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        renderPeriksa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renderPeriksa1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 170;
        gridBagConstraints.gridy = 50;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        add(renderPeriksa1, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nciz/RegisterRawatJalan/Gambar/logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 18;
        add(jLabel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasienActionPerformed
        // TODO add your handling code here:
        MenuUtamaEvent menuUtamaEvent;
        menuUtamaEvent = new MenuUtamaEvent(MenuUtamaListener.class);
        MenuUtamaListener[] listeners = listenerList.getListeners(MenuUtamaListener.class);
        for (MenuUtamaListener me : listeners) {
            me.pasien(menuUtamaEvent);
        }
    }//GEN-LAST:event_btnPasienActionPerformed

    private void renderPeriksa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renderPeriksa1ActionPerformed
        // TODO add your handling code here:
        MenuUtamaEvent menuUtamaEvent;
        menuUtamaEvent = new MenuUtamaEvent(MenuUtamaListener.class);
        MenuUtamaListener[] listeners = listenerList.getListeners(MenuUtamaListener.class);
        for (MenuUtamaListener me : listeners) {
            me.periksa(menuUtamaEvent);
        }
    }//GEN-LAST:event_renderPeriksa1ActionPerformed

    private void renderPembayaran1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renderPembayaran1ActionPerformed
        // TODO add your handling code here:
        MenuUtamaEvent menuUtamaEvent;
        menuUtamaEvent = new MenuUtamaEvent(MenuUtamaListener.class);
        MenuUtamaListener[] listeners = listenerList.getListeners(MenuUtamaListener.class);
        for (MenuUtamaListener me : listeners) {
            me.pembayaran(menuUtamaEvent);
        }
    }//GEN-LAST:event_renderPembayaran1ActionPerformed

    private void renderObat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renderObat1ActionPerformed
        // TODO add your handling code here:
        MenuUtamaEvent menuUtamaEvent;
        menuUtamaEvent = new MenuUtamaEvent(MenuUtamaListener.class);
        MenuUtamaListener[] listeners = listenerList.getListeners(MenuUtamaListener.class);
        for (MenuUtamaListener me : listeners) {
            me.obat(menuUtamaEvent);
        }
    }//GEN-LAST:event_renderObat1ActionPerformed

    private void renderDokter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renderDokter1ActionPerformed
        // TODO add your handling code here:
        MenuUtamaEvent menuUtamaEvent;
        menuUtamaEvent = new MenuUtamaEvent(MenuUtamaListener.class);
        MenuUtamaListener[] listeners = listenerList.getListeners(MenuUtamaListener.class);
        for (MenuUtamaListener me : listeners) {
            me.dokter(menuUtamaEvent);
        }
    }//GEN-LAST:event_renderDokter1ActionPerformed

    private void renderUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renderUser1ActionPerformed
        // TODO add your handling code here:
        MenuUtamaEvent menuUtamaEvent;
        menuUtamaEvent = new MenuUtamaEvent(MenuUtamaListener.class);
        MenuUtamaListener[] listeners = listenerList.getListeners(MenuUtamaListener.class);
        for (MenuUtamaListener me : listeners) {
            me.user(menuUtamaEvent);
        }
    }//GEN-LAST:event_renderUser1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Nciz.RegisterRawatJalan.frame.panel.RenderButton btnPasien;
    private javax.swing.JLabel jLabel3;
    private Nciz.RegisterRawatJalan.frame.panel.RenderDokter renderDokter1;
    private Nciz.RegisterRawatJalan.frame.panel.RenderObat renderObat1;
    private Nciz.RegisterRawatJalan.frame.panel.RenderPembayaran renderPembayaran1;
    private Nciz.RegisterRawatJalan.frame.panel.RenderPeriksa renderPeriksa1;
    private Nciz.RegisterRawatJalan.frame.panel.RenderUser renderUser1;
    // End of variables declaration//GEN-END:variables
}
