/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Nciz.RegisterRawatJalan.frame.panel;

import Nciz.RegisterRawatJalan.frame.RegRwtJalan;
import java.awt.CardLayout;

/**
 *
 * @author Ncizh
 */
public class MenuUtaman extends javax.swing.JPanel {

    private RegRwtJalan regRwtJalan;

    /**
     * Creates new form MenuUtaman
     */
    public MenuUtaman() {
        initComponents();
    }

    public void setRegRwtJalan(RegRwtJalan regRwtJalan) {
        this.regRwtJalan = regRwtJalan;
        menuAdmin1.setRegRwtJalan(regRwtJalan);
        menuAdmin1.setMenuUtaman(this);
        menuDokter1.setRegRwtJalan(regRwtJalan);
        menuDokter1.setMenuUtaman(this);
        menuPasien1.setRegRwtJalan(regRwtJalan);
        menuPasien1.setMenuUtaman(this);
        menuObat1.setRegRwtJalan(regRwtJalan);
        menuObat1.setMenuUtaman(this);
        menuPeriksa1.setRegRwtJalan(regRwtJalan);
        menuPeriksa1.setMenuUtaman(this);
        menuPembayaran1.setRegRwtJalan(regRwtJalan);
        menuPembayaran1.setMenuUtaman(this);
    }

    public void backMeuUtama() {
        CardLayout layout = (CardLayout) panelPivot1.getLayout();
        layout.show(panelPivot1, "cardLetakMenu");
        
        regRwtJalan.setLocationRelativeTo(null);
    }

    public LetakMenu getLetakMenu1() {
        return letakMenu1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPivot1 = new Nciz.RegisterRawatJalan.frame.panel.PanelPivot();
        letakMenu1 = new Nciz.RegisterRawatJalan.frame.panel.LetakMenu();
        menuPasien1 = new Nciz.RegisterRawatJalan.frame.panel.MenuPasien();
        menuPeriksa1 = new Nciz.RegisterRawatJalan.frame.panel.MenuPeriksa();
        menuObat1 = new Nciz.RegisterRawatJalan.frame.panel.MenuObat();
        menuAdmin1 = new Nciz.RegisterRawatJalan.frame.panel.MenuAdmin();
        menuDokter1 = new Nciz.RegisterRawatJalan.frame.panel.MenuDokter();
        menuPembayaran1 = new Nciz.RegisterRawatJalan.frame.panel.MenuPembayaran();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        panelPivot1.setLayout(new java.awt.CardLayout());

        letakMenu1.addUtamaListener(new Nciz.RegisterRawatJalan.event.MenuUtamaListener() {
            public void user(Nciz.RegisterRawatJalan.event.MenuUtamaEvent evt) {
                letakMenu1User(evt);
            }
            public void pembayaran(Nciz.RegisterRawatJalan.event.MenuUtamaEvent evt) {
                letakMenu1Pembayaran(evt);
            }
            public void periksa(Nciz.RegisterRawatJalan.event.MenuUtamaEvent evt) {
                letakMenu1Periksa(evt);
            }
            public void pasien(Nciz.RegisterRawatJalan.event.MenuUtamaEvent evt) {
                letakMenu1Pasien(evt);
            }
            public void obat(Nciz.RegisterRawatJalan.event.MenuUtamaEvent evt) {
                letakMenu1Obat(evt);
            }
            public void dokter(Nciz.RegisterRawatJalan.event.MenuUtamaEvent evt) {
                letakMenu1Dokter(evt);
            }
        });
        panelPivot1.add(letakMenu1, "cardLetakMenu");
        panelPivot1.add(menuPasien1, "cardPasien");
        panelPivot1.add(menuPeriksa1, "cardPeriksa");
        panelPivot1.add(menuObat1, "cardMenuObat");
        panelPivot1.add(menuAdmin1, "cardMenuAdmin");
        panelPivot1.add(menuDokter1, "cardMenuDokter");
        panelPivot1.add(menuPembayaran1, "cardPembayaran");

        add(panelPivot1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void letakMenu1Pasien(Nciz.RegisterRawatJalan.event.MenuUtamaEvent evt) {//GEN-FIRST:event_letakMenu1Pasien
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) panelPivot1.getLayout();
        layout.show(panelPivot1, "cardPasien");
        
        regRwtJalan.setLocationRelativeTo(null);
        menuPasien1.reloadDate();
    }//GEN-LAST:event_letakMenu1Pasien

    private void letakMenu1Periksa(Nciz.RegisterRawatJalan.event.MenuUtamaEvent evt) {//GEN-FIRST:event_letakMenu1Periksa
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) panelPivot1.getLayout();
        layout.show(panelPivot1, "cardPeriksa");
        
        regRwtJalan.setLocationRelativeTo(null);
        menuPeriksa1.reloadData();
        menuPeriksa1.reloadDataPeriksa();
        menuPeriksa1.reloadDokter();
    }//GEN-LAST:event_letakMenu1Periksa

    private void letakMenu1Obat(Nciz.RegisterRawatJalan.event.MenuUtamaEvent evt) {//GEN-FIRST:event_letakMenu1Obat
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) panelPivot1.getLayout();
        layout.show(panelPivot1, "cardMenuObat");
        
        regRwtJalan.setLocationRelativeTo(null);
        menuObat1.reloadData();
    }//GEN-LAST:event_letakMenu1Obat

    private void letakMenu1User(Nciz.RegisterRawatJalan.event.MenuUtamaEvent evt) {//GEN-FIRST:event_letakMenu1User
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) panelPivot1.getLayout();
        layout.show(panelPivot1, "cardMenuAdmin");
        
        regRwtJalan.setLocationRelativeTo(null);
        menuAdmin1.reload();
    }//GEN-LAST:event_letakMenu1User

    private void letakMenu1Dokter(Nciz.RegisterRawatJalan.event.MenuUtamaEvent evt) {//GEN-FIRST:event_letakMenu1Dokter
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) panelPivot1.getLayout();
        layout.show(panelPivot1, "cardMenuDokter");
        
        regRwtJalan.setLocationRelativeTo(null);
        menuDokter1.reloadData();
    }//GEN-LAST:event_letakMenu1Dokter

    private void letakMenu1Pembayaran(Nciz.RegisterRawatJalan.event.MenuUtamaEvent evt) {//GEN-FIRST:event_letakMenu1Pembayaran
        // TODO add your handling code here:
         CardLayout layout = (CardLayout) panelPivot1.getLayout();
        layout.show(panelPivot1, "cardPembayaran");
        
        regRwtJalan.setLocationRelativeTo(null);
        menuPembayaran1.reloadData();
    }//GEN-LAST:event_letakMenu1Pembayaran
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Nciz.RegisterRawatJalan.frame.panel.LetakMenu letakMenu1;
    private Nciz.RegisterRawatJalan.frame.panel.MenuAdmin menuAdmin1;
    private Nciz.RegisterRawatJalan.frame.panel.MenuDokter menuDokter1;
    private Nciz.RegisterRawatJalan.frame.panel.MenuObat menuObat1;
    private Nciz.RegisterRawatJalan.frame.panel.MenuPasien menuPasien1;
    private Nciz.RegisterRawatJalan.frame.panel.MenuPembayaran menuPembayaran1;
    private Nciz.RegisterRawatJalan.frame.panel.MenuPeriksa menuPeriksa1;
    private Nciz.RegisterRawatJalan.frame.panel.PanelPivot panelPivot1;
    // End of variables declaration//GEN-END:variables
}
