/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Nciz.RegisterRawatJalan.frame;

import Nciz.RegisterRawatJalan.frame.panel.MenuUtaman;
import com.stripbandunk.jglasspane.component.MessageComponent;
import javax.swing.JFrame;

/**
 *
 * @author Ncizh
 */
public class RegRwtJalan extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public RegRwtJalan() {
        initComponents();
        setGlassPane(jGlassPane1);
        jGlassPane1.addGlassPaneComponent(messageComponent1);
        getGlassPane().setVisible(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        
    }

    public MessageComponent getMessageComponent1() {
        return messageComponent1;
    }

    public MenuUtaman getMenuUtaman1() {
        return menuUtaman1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGlassPane1 = new com.stripbandunk.jglasspane.JGlassPane();
        messageComponent1 = new com.stripbandunk.jglasspane.component.MessageComponent();
        jPanelImageBackground1 = new wordpress.eecchhoo.jpanelimagebackground.JPanelImageBackground();
        menuUtaman1 = new Nciz.RegisterRawatJalan.frame.panel.MenuUtaman();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Puskesmas Winduaji\n");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelImageBackground1.setGambar(new java.io.File("E:\\Zona Terlarang\\images\\Wallpaper dengan corak menarik\\929678-1366x768-blue-water-ripple.jpg"));
        jPanelImageBackground1.setGambarDrawType(1);
        jPanelImageBackground1.setLayout(new java.awt.BorderLayout());
        jPanelImageBackground1.add(menuUtaman1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelImageBackground1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        menuUtaman1.setRegRwtJalan(this);
        
        
    }//GEN-LAST:event_formWindowOpened
     
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.stripbandunk.jglasspane.JGlassPane jGlassPane1;
    private wordpress.eecchhoo.jpanelimagebackground.JPanelImageBackground jPanelImageBackground1;
    private Nciz.RegisterRawatJalan.frame.panel.MenuUtaman menuUtaman1;
    private com.stripbandunk.jglasspane.component.MessageComponent messageComponent1;
    // End of variables declaration//GEN-END:variables
}
